//
// Created by lamine on 07-09-2021.
//

#ifndef GOL_GAME_H
#define GOL_GAME_H

#define TAILLE_SQUARE         25
#define NB_SQUARE_LARGEUR     50
#define NB_SQUARE_HAUTEUR     35
#define LARGEUR_FENETRE       NB_SQUARE_LARGEUR * TAILLE_SQUARE
#define HAUTEUR_FENETRE       NB_SQUARE_HAUTEUR * TAILLE_SQUARE
#define NB_SQUARE             NB_SQUARE_LARGEUR * NB_SQUARE_HAUTEUR

#endif //GOL_GAME_H
